// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/(auth)/login.tsx';
import * as $1 from './routes/(auth)/register.tsx';
import * as $2 from './routes/(marketing)/privacy.ts';
import * as $3 from './routes/(marketing)/terms.ts';
import * as $4 from './routes/_404.tsx';
import * as $5 from './routes/_app.tsx';
import * as $6 from './routes/_layout.tsx';
import * as $7 from './routes/_middleware.ts';
import * as $8 from './routes/api/og.tsx';
import * as $9 from './routes/api/trpc/[...path].ts';
import * as $10 from './routes/index.tsx';
import * as $$0 from './islands/Counter.tsx';
import * as $$1 from './islands/Fetch.tsx';

const manifest = {
    routes: {
        './routes/(auth)/login.tsx': $0,
        './routes/(auth)/register.tsx': $1,
        './routes/(marketing)/privacy.ts': $2,
        './routes/(marketing)/terms.ts': $3,
        './routes/_404.tsx': $4,
        './routes/_app.tsx': $5,
        './routes/_layout.tsx': $6,
        './routes/_middleware.ts': $7,
        './routes/api/og.tsx': $8,
        './routes/api/trpc/[...path].ts': $9,
        './routes/index.tsx': $10,
    },
    islands: {
        './islands/Counter.tsx': $$0,
        './islands/Fetch.tsx': $$1,
    },
    baseUrl: import.meta.url,
};

export default manifest;
